main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from auth_app.views import register_view, login_view, logout_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts_app.urls", namespace="Post")),
    path("register/", register_view, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout")
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts_app/urls.py
from django.urls import path

from posts_app.views import index, create_post, delete_post, reply_post

app_name = "Post"

urlpatterns = [
    path("", index, name="home"),
    path("create/", create_post, name="create"),
    path("<int:pk>/delete", delete_post, name="delete"),
    path("<int:pk>/reply", reply_post, name="reply")
]

templates/posts/components/post-list.html
{% if posts %}
  {% for post in posts %}
      {% include "posts/components/post-structure.html" with post=post %}
  {% endfor %}
{% else %}
  No posts created
{% endif %}

templates/posts/components/post-navbar.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/components/navbar.css' %}">
<div class="navbar-main navbar-secondary">
  <div class="navbar-left">
<!--    <div class="navbar-block-non-active">by date:</div>-->
<!--    <a href="{% url 'Post:home' %}?sort_by_date=new" class="navbar-block">new</a>-->
<!--    <a href="{% url 'Post:home' %}?sort_by_date=old" class="navbar-block">old</a>-->

<!--    <div></div>-->
<!--    <form action="{% url 'Post:home' %}" method="GET">-->
<!--    <label for="username">Filter by Username:</label>-->
<!--    <input type="text" id="username" name="username_starts_with" placeholder="Enter username starts with...">-->
<!--    <button type="submit" class="navbar-block">Apply Filter</button>-->
<!--    </form>-->

<!--    <form action="{% url 'Post:home' %}" method="GET" class="navbar-form">-->
<!--    <div style="display: flex; flex-direction: row">-->
<!--        <label>by date:</label>-->
<!--        <div style="display: flex; flex-direction: column">-->
<!--          <div>-->
<!--            <input type="radio" id="new" name="sort_by_date" value="new">-->
<!--            <label for="new">New</label>-->
<!--          </div>-->
<!--          <div>-->
<!--            <input type="radio" id="old" name="sort_by_date" value="old">-->
<!--            <label for="old">Old</label>-->
<!--          </div>-->
<!--        </div>-->
<!--    </div>-->

<!--    <div>-->
<!--        <label for="username">by username:</label>-->
<!--        <input type="text" id="username" name="username_starts_with" placeholder="..." style="width: 30px">-->
<!--    </div>-->

<!--    <div>-->
<!--        <button type="submit">Apply</button>-->
<!--    </div>-->
<!--    </form>-->

    <form action="{% url 'Post:home' %}" method="GET" class="navbar-form">
      <label>Sort by date:</label>
    <div class="tabs">
      <input class="tab-input" type="radio" id="radio-1" name="sort_by_date" value="new">
      <label class="tab-label" for="radio-1">new</label>
      <input class="tab-input" type="radio" id="radio-2" name="sort_by_date" value="old">
      <label class="tab-label" for="radio-2">old</label>
    </div>


    <div>
        <label for="username"></label>
        <input type="text" id="username" name="username_filter" placeholder="username" class="navbar-form-input">
    </div>

    <div>
        <button type="submit">Apply</button>
    </div>
    </form>







  </div>
  <div class="navbar-right">
    {% if user.is_authenticated %}
      <a href="{% url 'Post:home' %}" class="navbar-block">My posts</a>
    {% endif %}
    <a href="{% url 'Post:create' %}" class="navbar-block">+ Create</a>
  </div>
</div>

templates/posts/components/post-structure.html
{% load static %}

<div class="post-main">
  <div class="post-owner-field">
    <div class="post-owner">{{ post.owner.username }}</div>
  </div>

  <div class="post-body">
    <div class="post-text">{{ post.clean_text|safe }}</div>
    {% if post.attachment %}
      <div>
        {% if post.attachment_type == "image" %}
          <img src="{{ post.attachment.url }}" alt="image" class="post-image">
        {% elif post.attachment_type == "txt" %}
          <textarea readonly class="post-txt">{{ post.text_file_content_as_html }}</textarea>
        {% endif %}
      </div>
    {% endif %}

    <div class="post-panel">
      <div class="post-panel-left">
        <a href="{% url 'Post:reply' pk=post.pk %}" class="post-panel-control">Reply</a>
      </div>

      <div class="post-panel-right">
        {% if post.owner == user %}
          <a href="{% url 'Post:delete' pk=post.pk %}" class="post-panel-control">Delete</a>
        {% endif %}
      </div>
    </div>
  </div>

  {% include "posts/components/recursive_replies.html" %}
</div>

templates/posts/components/recursive_replies.html
{% if post.replies.exists %}
    {% if not is_reply %}
      <div class="reply-block">
    {% endif %}

    {% include "posts/components/reply-loop.html" %}

    {% if not is_reply %}
      </div>
    {% endif %}
        
{% endif %}

templates/posts/components/reply-loop.html
{% for reply in post.replies.all %}
{% include "posts/components/reply-structure.html" with post=reply is_reply=True %}
{% endfor %}

templates/posts/components/reply-structure.html
{% load static %}

<div class="reply-wrap">
  <div class="reply-pointer">
    <div class="reply-pointer-second"></div>
  </div>

  <div class="reply-main">
    <div class="post-owner-field">
      <div class="post-owner">{{ post.owner.username }} <div class="reply-mark">replied</div></div>
    </div>

    <div class="post-body">
      <div class="post-text">{{ post.clean_text|safe }}</div>
      {% if post.attachment %}
        <div>
        {% if post.attachment_type == "image" %}
          <img src="{{ post.attachment.url }}" alt="image" class="post-image">
        {% elif post.attachment_type == "txt" %}
          <textarea readonly class="post-txt">{{ post.text_file_content_as_html }}</textarea>
        {% endif %}
      </div>
      {% endif %}

      <div class="post-panel">
        <div class="post-panel-left">
          <a href="{% url 'Post:reply' pk=post.pk %}" class="post-panel-control">Reply</a>
        </div>

        <div class="post-panel-right">
          {% if post.owner == user %}
            <a href="{% url 'Post:delete' pk=post.pk %}" class="post-panel-control">Delete</a>
          {% endif %}
        </div>
      </div>
    </div>

    {% include "posts/components/recursive_replies.html" %}
  </div>
</div>